// This file is auto-generated by scripts/gen-types.sh
// Do not edit manually. Run 'bash scripts/gen-types.sh' to regenerate.
// Generated at: 2026-03-05T23:15:34Z

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.1"
  }
  public: {
    Tables: {
      app_admin: {
        Row: {
          created_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          user_id?: string
        }
        Relationships: []
      }
      boards: {
        Row: {
          anon_mode: string
          created_at: string
          description: string | null
          group_id: number | null
          id: number
          name: string
          updated_at: string
          visibility: string
        }
        Insert: {
          anon_mode?: string
          created_at?: string
          description?: string | null
          group_id?: number | null
          id?: number
          name: string
          updated_at?: string
          visibility?: string
        }
        Update: {
          anon_mode?: string
          created_at?: string
          description?: string | null
          group_id?: number | null
          id?: number
          name?: string
          updated_at?: string
          visibility?: string
        }
        Relationships: [
          {
            foreignKeyName: "boards_group_id_fkey"
            columns: ["group_id"]
            isOneToOne: false
            referencedRelation: "groups"
            referencedColumns: ["id"]
          },
        ]
      }
      comments: {
        Row: {
          author_id: string
          board_id: number | null
          content: string
          created_at: string
          deleted_at: string | null
          display_name: string
          group_id: number | null
          id: number
          is_anonymous: boolean
          post_id: number
          updated_at: string
        }
        Insert: {
          author_id: string
          board_id?: number | null
          content: string
          created_at?: string
          deleted_at?: string | null
          display_name?: string
          group_id?: number | null
          id?: number
          is_anonymous?: boolean
          post_id: number
          updated_at?: string
        }
        Update: {
          author_id?: string
          board_id?: number | null
          content?: string
          created_at?: string
          deleted_at?: string | null
          display_name?: string
          group_id?: number | null
          id?: number
          is_anonymous?: boolean
          post_id?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "comments_board_id_fkey"
            columns: ["board_id"]
            isOneToOne: false
            referencedRelation: "boards"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "comments_group_id_fkey"
            columns: ["group_id"]
            isOneToOne: false
            referencedRelation: "groups"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "comments_post_id_fkey"
            columns: ["post_id"]
            isOneToOne: false
            referencedRelation: "posts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "comments_post_id_fkey"
            columns: ["post_id"]
            isOneToOne: false
            referencedRelation: "posts_with_like_count"
            referencedColumns: ["id"]
          },
        ]
      }
      group_members: {
        Row: {
          group_id: number
          id: number
          joined_at: string
          left_at: string | null
          nickname: string | null
          role: string
          status: string
          user_id: string
        }
        Insert: {
          group_id: number
          id?: never
          joined_at?: string
          left_at?: string | null
          nickname?: string | null
          role?: string
          status?: string
          user_id: string
        }
        Update: {
          group_id?: number
          id?: never
          joined_at?: string
          left_at?: string | null
          nickname?: string | null
          role?: string
          status?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "group_members_group_id_fkey"
            columns: ["group_id"]
            isOneToOne: false
            referencedRelation: "groups"
            referencedColumns: ["id"]
          },
        ]
      }
      groups: {
        Row: {
          created_at: string
          description: string | null
          id: number
          invite_code: string | null
          join_mode: string
          name: string
          owner_id: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          id?: number
          invite_code?: string | null
          join_mode?: string
          name: string
          owner_id?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          description?: string | null
          id?: number
          invite_code?: string | null
          join_mode?: string
          name?: string
          owner_id?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      post_analysis: {
        Row: {
          analyzed_at: string
          emotions: string[]
          id: number
          post_id: number
        }
        Insert: {
          analyzed_at?: string
          emotions?: string[]
          id?: number
          post_id: number
        }
        Update: {
          analyzed_at?: string
          emotions?: string[]
          id?: number
          post_id?: number
        }
        Relationships: [
          {
            foreignKeyName: "post_analysis_post_id_fkey"
            columns: ["post_id"]
            isOneToOne: true
            referencedRelation: "posts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "post_analysis_post_id_fkey"
            columns: ["post_id"]
            isOneToOne: true
            referencedRelation: "posts_with_like_count"
            referencedColumns: ["id"]
          },
        ]
      }
      posts: {
        Row: {
          author_id: string
          board_id: number | null
          content: string
          created_at: string
          deleted_at: string | null
          display_name: string
          group_id: number | null
          id: number
          image_url: string | null
          initial_emotions: string[] | null
          is_anonymous: boolean
          member_id: number | null
          title: string
          updated_at: string
        }
        Insert: {
          author_id: string
          board_id?: number | null
          content: string
          created_at?: string
          deleted_at?: string | null
          display_name?: string
          group_id?: number | null
          id?: number
          image_url?: string | null
          initial_emotions?: string[] | null
          is_anonymous?: boolean
          member_id?: number | null
          title: string
          updated_at?: string
        }
        Update: {
          author_id?: string
          board_id?: number | null
          content?: string
          created_at?: string
          deleted_at?: string | null
          display_name?: string
          group_id?: number | null
          id?: number
          image_url?: string | null
          initial_emotions?: string[] | null
          is_anonymous?: boolean
          member_id?: number | null
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "posts_board_id_fkey"
            columns: ["board_id"]
            isOneToOne: false
            referencedRelation: "boards"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "posts_group_id_fkey"
            columns: ["group_id"]
            isOneToOne: false
            referencedRelation: "groups"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "posts_member_id_fkey"
            columns: ["member_id"]
            isOneToOne: false
            referencedRelation: "group_members"
            referencedColumns: ["id"]
          },
        ]
      }
      reactions: {
        Row: {
          count: number
          id: number
          post_id: number
          reaction_type: string
        }
        Insert: {
          count?: number
          id?: number
          post_id: number
          reaction_type: string
        }
        Update: {
          count?: number
          id?: number
          post_id?: number
          reaction_type?: string
        }
        Relationships: [
          {
            foreignKeyName: "reactions_post_id_fkey"
            columns: ["post_id"]
            isOneToOne: false
            referencedRelation: "posts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reactions_post_id_fkey"
            columns: ["post_id"]
            isOneToOne: false
            referencedRelation: "posts_with_like_count"
            referencedColumns: ["id"]
          },
        ]
      }
      user_preferences: {
        Row: {
          created_at: string | null
          notification_enabled: boolean | null
          onboarding_completed: boolean | null
          preferred_emotions: string[] | null
          theme_preference: string | null
          updated_at: string | null
          user_id: string
        }
        Insert: {
          created_at?: string | null
          notification_enabled?: boolean | null
          onboarding_completed?: boolean | null
          preferred_emotions?: string[] | null
          theme_preference?: string | null
          updated_at?: string | null
          user_id: string
        }
        Update: {
          created_at?: string | null
          notification_enabled?: boolean | null
          onboarding_completed?: boolean | null
          preferred_emotions?: string[] | null
          theme_preference?: string | null
          updated_at?: string | null
          user_id?: string
        }
        Relationships: []
      }
      user_reactions: {
        Row: {
          created_at: string | null
          id: number
          post_id: number
          reaction_type: string
          user_id: string
        }
        Insert: {
          created_at?: string | null
          id?: number
          post_id: number
          reaction_type: string
          user_id: string
        }
        Update: {
          created_at?: string | null
          id?: number
          post_id?: number
          reaction_type?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_reactions_post_id_fkey"
            columns: ["post_id"]
            isOneToOne: false
            referencedRelation: "posts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_reactions_post_id_fkey"
            columns: ["post_id"]
            isOneToOne: false
            referencedRelation: "posts_with_like_count"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      posts_with_like_count: {
        Row: {
          author_id: string | null
          board_id: number | null
          comment_count: number | null
          content: string | null
          created_at: string | null
          display_name: string | null
          emotions: string[] | null
          group_id: number | null
          id: number | null
          image_url: string | null
          initial_emotions: string[] | null
          is_anonymous: boolean | null
          like_count: number | null
          member_id: number | null
          title: string | null
        }
        Relationships: [
          {
            foreignKeyName: "posts_board_id_fkey"
            columns: ["board_id"]
            isOneToOne: false
            referencedRelation: "boards"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "posts_group_id_fkey"
            columns: ["group_id"]
            isOneToOne: false
            referencedRelation: "groups"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "posts_member_id_fkey"
            columns: ["member_id"]
            isOneToOne: false
            referencedRelation: "group_members"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Functions: {
      cleanup_orphan_group_members: {
        Args: { days_inactive?: number }
        Returns: number
      }
      get_emotion_timeline: {
        Args: { p_days?: number }
        Returns: {
          cnt: number
          day: string
          emotion: string
        }[]
      }
      get_emotion_trend: {
        Args: { days?: number }
        Returns: {
          cnt: number
          emotion: string
          pct: number
        }[]
      }
      get_my_activity_summary: { Args: never; Returns: Json }
      get_post_reactions: {
        Args: { p_post_id: number }
        Returns: {
          count: number
          reaction_type: string
          user_reacted: boolean
        }[]
      }
      get_posts_by_emotion: {
        Args: { p_emotion: string; p_limit?: number; p_offset?: number }
        Returns: {
          author_id: string
          board_id: number
          comment_count: number
          content: string
          created_at: string
          display_name: string
          emotions: string[]
          group_id: number
          id: number
          image_url: string
          initial_emotions: string[]
          is_anonymous: boolean
          like_count: number
          title: string
        }[]
      }
      get_recommended_posts_by_emotion: {
        Args: { p_limit?: number; p_post_id: number }
        Returns: {
          board_id: number
          comment_count: number
          created_at: string
          emotions: string[]
          id: number
          like_count: number
          score: number
          title: string
        }[]
      }
      get_similar_feeling_count: {
        Args: { p_days?: number; p_post_id: number }
        Returns: number
      }
      get_trending_posts: {
        Args: { p_hours?: number; p_limit?: number }
        Returns: {
          board_id: number
          comment_count: number
          created_at: string
          display_name: string
          emotions: string[]
          id: number
          like_count: number
          score: number
          title: string
        }[]
      }
      get_user_emotion_calendar: {
        Args: { p_end?: string; p_start?: string; p_user_id: string }
        Returns: {
          day: string
          emotions: string[]
          post_count: number
        }[]
      }
      is_group_member: { Args: { p_group_id: number }; Returns: boolean }
      search_posts: {
        Args: { p_limit?: number; p_offset?: number; p_query: string }
        Returns: {
          author_id: string
          board_id: number
          comment_count: number
          content: string
          created_at: string
          display_name: string
          emotions: string[]
          group_id: number
          id: number
          image_url: string
          initial_emotions: string[]
          is_anonymous: boolean
          like_count: number
          title: string
        }[]
      }
      show_limit: { Args: never; Returns: number }
      show_trgm: { Args: { "": string }; Returns: string[] }
      soft_delete_comment: {
        Args: { p_comment_id: number }
        Returns: undefined
      }
      soft_delete_post: { Args: { p_post_id: number }; Returns: undefined }
      toggle_reaction: {
        Args: { p_post_id: number; p_type: string }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
